DATA:
  data_name: shapenet
  data_root: /nvme_disk/phy/ICCV_2023/P2P_ICCV/data
  classes: 16
  npoints: 2048
  use_normals: False


BaseModel:
  base_model_variant: convnext_base
  head_type: pooling_mlp  # linear pooling_mlp mlp
  mlp_dropout_ratio: 0.5
  mlp_mid_channels: [512, 256]
  view_feature: 1024
  num_features: 1024
  num_head_features: 4096
  obj_size: 224
  img_size: 224
  checkpoint_path:

Enc:
  atten_fusion: True
  local_size: 32
  trans_dim: 8
  graph_dim: 64
  imgblock_dim: 64
  imagenet_default_mean: [0.485, 0.456, 0.406]
  imagenet_default_std: [0.229, 0.224, 0.225]

TRAIN:
  update_type: norm
  label_smoothing: True

  train_gpu: [5]
  workers: 4
  batch_size: 16
  batch_size_val: 16
  num_shots: 16
  num_views: 4

  lr: 5e-4
  weight_decay: 0.05
  epochs: 300
  val_epoch: 200
  last_epochs: 30
  start_epoch: 0
  warmup_epochs: 0
  scheduler: CosLR
  amp: False

  manual_seed: 1463
  print_freq: 40
  save_freq: 10
  save_path: checkpoint_test
  pretrained: 
  weight:  # path to initial weight (default: none)
  resume: 
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 10

Distributed:
  dist_url: tcp://127.0.0.1:3809
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0


TEST:
  test_workers: 0
  test_gpu: [0]
  test_batch_size: 12
  model_path: checkpoint_modelnet40_convnext_atten_fusion_conv_fusion/experiment_convnext-L_fewshot_4_view_4_shot_transformer_32token_conv_fusion_GELU_linear/model/model_best.pth
  save_folder:
